server:
  port: 4545

spring:
  application:
    name: wigell-gateway

  cloud:
    gateway:
<<<<<<< HEAD
      routes:
        - id: wigell-repairs
          uri: http://wigell-repairs:5555

          predicates:
            - Path=/api/wigellrepairs/**
=======
      server:
        webmvc:
          routes:
        # Route to Wigell Repairs microservice
           - id: wigell-repairs
             uri: http://wigell-repairs:5555
          predicates:  Path=/api/wigellrepairs/**



>>>>>>> origin/main
